name: create issue
on:
  schedule:
    - cron:  '0 0 1 */3 *'

on:
  workflow_dispatch:

# 権限設定を追加
permissions:
  issues: write
  contents: read

jobs:
  build:
    name: create issue
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
